### ISSUE TITLE
How do you run tensorboard on the DNC program? it asks for  arguments when I run tensorboard when main.py is running

### ISSUE THREAD

**Issue by josheeg** [bgavran/DNC#6]
How do you run tensorboard on the DNC program? it asks for  arguments when I run tensorboard when main.py is running.

So this is what I see in your paper I go to the command line and hit tensorboard

To start the DNC with feedforward controller on the copy task with curriculum learning just run the main.py file. It should work out of the box and all the memory operations will be automatically visualized in Tensorboard.

Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 11, in <module>
    sys.exit(run_main())
  File "/home/joshua/.local/lib/python3.6/site-packages/tensorboard/main.py", line 36, in run_main
    tf.app.run(main)
  File "/home/joshua/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/joshua/.local/lib/python3.6/site-packages/tensorboard/main.py", line 45, in main
    default.get_assets_zip_provider())
  File "/home/joshua/.local/lib/python3.6/site-packages/tensorboard/program.py", line 165, in main
    tb = create_tb_app(plugins, assets_zip_provider)
  File "/home/joshua/.local/lib/python3.6/site-packages/tensorboard/program.py", line 189, in create_tb_app
    raise ValueError('A logdir must be specified when db is not specified. '
ValueError: A logdir must be specified when db is not specified. Run `tensorboard --help` for details and examples.

**Comment by bgavran** [comment]
You need to provide a log directory. Try running
`tensorboard --logdir=log`

and see if that works.

**Comment by josheeg** [comment]
I see a link I started running it before and after I start the python3
main.py
should I have it in the main directory or something?
should I run tensorboard3?

On Sat, Mar 10, 2018 at 11:25 AM, Bruno Gavranović <notifications@github.com
